//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAsociacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pagos
    {
        public int id_pago { get; set; }
        public int id_persona { get; set; }
        public decimal valor_pago { get; set; }
        public System.DateTime fecha_pago { get; set; }
    
        public virtual personas personas { get; set; }
    }
}
