//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAsociacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            this.detalle_pagos = new HashSet<detalle_pagos>();
        }
    
        public int id_persona { get; set; }
        public string dni_persona { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string direccion_residencia { get; set; }
        public string ciudad_residencia { get; set; }
        public int telefono_celular { get; set; }
        public string profesion { get; set; }
        public System.DateTime fecha_vinculacion { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public System.DateTime fecha_salida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pagos> detalle_pagos { get; set; }
    }
}
