//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAsociacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_login
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string pass_usuario { get; set; }
    }
}
